### ISSUE TITLE
Include path issues when building on Windows

### ISSUE THREAD

**Issue by lparsons** [eugenemel/maven_core#2]
```
make[2]: *** [Makefile.Debug:22799: tmp/classifier.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from stable.h:76:0,
                 from mainwindow.h:4,
                 from mainwindow.cpp:1:
../libmaven/mzSample.h:37:22: fatal error: MSReader.h: No such file or directory
 #include "MSReader.h"
                      ^
compilation terminated.
```

I see there have been some changes regarding MSToolkit recently, so I started looking there, but I haven't yet figured out what is missing/wrong.

**Comment by lparsons** [comment]
Looking at this a bit further, I think it might really be an issue with `maven` and not `maven_core`. I'm trying to build with the latest `maven`, though I think the submodule points to an older version (without the Win32 fix in the project file).

**Comment by lparsons** [comment]
Hmmm... was able to get past this by adding `../MSToolkit/include` to the libmnaven include path, but then I run into a problem linking with various zlib functions not being found... I saw a reference to `../zlib/` in libmaven's include, but that's not actually in the repo (nor the `.pro` files). Any suggestions?

**Comment by eugenemel** [comment]
Hi Lance,  confirmed the issue, missing path in INCLUDE in maven.pro.  I just fixed it. Thank you for reporting the issue.

**Comment by lparsons** [comment]
Thanks @eugenemel. I had gotten that far, but now I getting `undefined reference` errors which I'm pretty sure have to do with zlib. I've installed various zlib packages in MSYS2 (using pacman), but so far it hasn't fixed anything.

```
make -f Makefile.Debug
make[1]: Entering directory '/home/Lance Parsons/maven_core/maven'
linking ../bin/maven_dev_20170509.exe
C:/msys64/home/Lance Parsons/maven_core/build/lib/libmstoolkitlite.a(MSReader.o): In function `MSToolkit::MSReader::writeCompressSpec(_iobuf*, MSToolkit::Spectrum&)':
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/MSToolkit/MSReader.cpp:1885: undefined reference to `compressBound'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/MSToolkit/MSReader.cpp:1887: undefined reference to `compress'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/MSToolkit/MSReader.cpp:1892: undefined reference to `compressBound'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/MSToolkit/MSReader.cpp:1894: undefined reference to `compress'
C:/msys64/home/Lance Parsons/maven_core/build/lib/libmstoolkitlite.a(MSReader.o): In function `MSToolkit::MSReader::readCompressSpec(_iobuf*, MSToolkit::MSScanInfo&, MSToolkit::Spectrum&)':
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/MSToolkit/MSReader.cpp:1932: undefined reference to `uncompress'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/MSToolkit/MSReader.cpp:1939: undefined reference to `uncompress'
C:/msys64/home/Lance Parsons/maven_core/build/lib/libmstoolkitlite.a(saxmzxmlhandler.o): In function `mzpSAXMzxmlHandler::decompress32()':
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/saxmzxmlhandler.cpp:368: undefined reference to `uncompress'
C:/msys64/home/Lance Parsons/maven_core/build/lib/libmstoolkitlite.a(saxmzxmlhandler.o): In function `mzpSAXMzxmlHandler::decompress64()':
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/saxmzxmlhandler.cpp:408: undefined reference to `uncompress'
C:/msys64/home/Lance Parsons/maven_core/build/lib/libmstoolkitlite.a(Czran.o): In function `Czran::build_index(_iobuf*, long long, gz_access**)':
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:150: undefined reference to `inflateInit2_'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:185: undefined reference to `inflate'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:219: undefined reference to `inflateEnd'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:227: undefined reference to `inflateEnd'
C:/msys64/home/Lance Parsons/maven_core/build/lib/libmstoolkitlite.a(Czran.o): In function `Czran::extract(_iobuf*, long long)':
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:263: undefined reference to `inflateInit2_'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:275: undefined reference to `inflatePrime'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:277: undefined reference to `inflateSetDictionary'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:308: undefined reference to `inflate'
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/Czran.cpp:324: undefined reference to `inflateEnd'
C:/msys64/home/Lance Parsons/maven_core/build/lib/libmstoolkitlite.a(saxmzmlhandler.o): In function `mzpSAXMzmlHandler::decode(std::vector<double, std::allocator<double> >&)':
C:\msys64\home\Lance Parsons\maven_core\MSToolkit/src/mzParser/saxmzmlhandler.cpp:645: undefined reference to `uncompress'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile.Debug:297: ../bin/maven_dev_20170509.exe] Error 1
make[1]: Leaving directory '/home/Lance Parsons/maven_core/maven'
make: *** [Makefile:34: debug] Error 2
```

**Comment by eugenemel** [comment]
Agree, this is zlib link error. I would not mind packaging our own zlib with distribution, but would like to avoid doing so.. Let me see if I can figure this out and come back to you.

**Comment by lparsons** [comment]
I complete agree about avoiding packaging zlib, it'd be nice to avoid but OK if necessary.

One thing I'd really like to do is setup some sort of continuous integration environment to at least do builds on Windows/OSX/Linux. Let me know if that's something you'd be OK with/interested in. I'd have to review options, but at the very least I know we'd be able to setup a [Jenkins](https://jenkins.io/) system here.

**Comment by eugenemel** [comment]
Tried a bunch of thing to fix the issue.. various LIBS options and compile flags, but the damn thing is refusing to cooperate. I think the solution will be to package zlib after all, I used to do that many release ago, so should be easy enough to get it working.    

Agree 100% on continues integration idea.. is it a lot of work to get it running on Windows / OSX? 

Eugene.

**Comment by lparsons** [comment]
OK, well at least it wasn't just me... ;-) Shall I work on putting zlib in there, or are you handling that?

As for CI, the trick would be Windows. Travis is pretty simple for Linux and I'm pretty sure OSX, but they don't offer Windows. There are others that do, but not sure how they work. If you're OK with us (Princeton) hosting some machines to actually run the CI stuff, Jenkins is very customization (since you're responsible for setting up the compute) and we have some institutional support for it here. I'll come up with some options and we can decide.
