### ISSUE TITLE
Setup Windows CI service for building

### ISSUE THREAD

**Issue by lparsons** [eugenemel/maven_core#4]
This is an issue to track the work on setting up a CI service to build a Windows application as originally discussed in https://github.com/eugenemel/maven_core/issues/2.

**Comment by lparsons** [comment]
I'm current investigating [AppVeyor](https://ci.appveyor.com/) which seems fairly promising. Travis can of course be used for Linux and OSX once this is done.

**Comment by lparsons** [comment]
PR #5 addresses this issue. Once it is merged and the Appveyor setup is complete, we can close this issue.

**Comment by eugenemel** [comment]
Hi Lance, if I understand correctly you were able to get builds running in Appveyor? So all is good?

**Comment by lparsons** [comment]
It seems like you still need to sign up and authorize Appveyor to this repository. It's just a few steps, the configuration is all in the `appveyor.yml` file. I have it running on my fork, but I don't have permission to this repository to set it up.

**Comment by lparsons** [comment]
Looks to be running (and should pass soon, pending https://github.com/eugenemel/maven/pull/5).
